server:
    port: 8083

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: book-service-route
                  uri: lb://BOOK
                  predicates:
                      - Path=/books/**
                - id: order-service-route
                  uri: lb://ORDER
                  predicates:
                      - Path=/orders/**
                - id: user-service-route
                  uri: lb://USER
                  predicates:
                      - Path=/users/**


eureka:
    client:
        service-url:
            defaultZone: http://eureka-server:8761/eureka
        fetch-registry: true
        register-with-eureka: true